using System.ComponentModel.DataAnnotations;
using QUALITE.Models.PrincipalEntity;
using  QUALITE.Models.RegularEntity;
namespace QUALITE.Services.WeakServices;

public class L1Services
{
	[Required(ErrorMessage ="Code L1 obligatoire")]
	public int Code {get;set;}
	[Required(ErrorMessage ="Code Etablissement obligatoire")]
	public int CodeEtab {get;set;}
    public Etablissement? Etablissement {get;set;}
	[Required(ErrorMessage ="Code FPE obligatoire")]
	public int CodeFpe {get;set;}
    public ModelFpe? ModelFpe {get;set;}
	public int RAMENER_FRANCAIS { get; set; }
	public int RAMENER_MALAGASY { get; set; }
	public int SERIES_VOLA_T1 { get; set; }
	public int SERIES_VOLA_T2 { get; set; }
	public int SERIES_VOLA_T3 { get; set; }
	public int SERIES_VOLA_T4 { get; set; }
	public int SERIES_VOLA_T5 { get; set; }
	public int RAKIBOLANA_T1 { get; set; }
	public int RAKIBOLANA_T2 { get; set; }
	public int RAKIBOLANA_T3 { get; set; }
	public int RAKIBOLANA_T4 { get; set; }
	public int RAKIBOLANA_T5 { get; set; }
	public int MALAGASY_T1 { get; set; }
	public int MALAGASY_T2 { get; set; }
	public int MALAGASY_T3 { get; set; }
	public int MALAGASY_T4 { get; set; }
	public int MALAGASY_T5 { get; set; }
	public int MALAGASY_T6 { get; set; }
	public int MALAGASY_T7 { get; set; }
	public int MALAGASY_T8 { get; set; }
	public int MALAGASY_T9 { get; set; }
	public int MALAGASY_2NDE { get; set; }
	public int MALAGASY_1A { get; set; }
	public int MALAGASY_1C { get; set; }
	public int MALAGASY_1D { get; set; }
	public int MALAGASY_1L { get; set; }
	public int MALAGASY_1S { get; set; }
	public int MALAGASY_1OSE { get; set; }
	public int MALAGASY_TA { get; set; }
	public int MALAGASY_TC { get; set; }
	public int MALAGASY_TD { get; set; }
	public int MALAGASY_TL { get; set; }
	public int MALAGASY_TS { get; set; }
	public int MALAGASY_TOSE { get; set; }
	public int FRANCAIS_T1 { get; set; }
	public int FRANCAIS_T2 { get; set; }
	public int FRANCAIS_T3 { get; set; }
	public int FRANCAIS_T4 { get; set; }
	public int FRANCAIS_T5 { get; set; }
	public int FRANCAIS_T6 { get; set; }
	public int FRANCAIS_T7 { get; set; }
	public int FRANCAIS_T8 { get; set; }
	public int FRANCAIS_T9 { get; set; }
	public int FRANCAIS_2NDE { get; set; }
	public int FRANCAIS_1A { get; set; }
	public int FRANCAIS_1C { get; set; }
	public int FRANCAIS_1D { get; set; }
	public int FRANCAIS_1L { get; set; }
	public int FRANCAIS_1S { get; set; }
	public int FRANCAIS_1OSE { get; set; }
	public int FRANCAIS_TA { get; set; }
	public int FRANCAIS_TC { get; set; }
	public int FRANCAIS_TD { get; set; }
	public int FRANCAIS_TL { get; set; }
	public int FRANCAIS_TS { get; set; }
	public int FRANCAIS_TOSE { get; set; }
	public int HISTOIRE_T1 { get; set; }
	public int HISTOIRE_T2 { get; set; }
	public int HISTOIRE_T3 { get; set; }
	public int HISTOIRE_T4 { get; set; }
	public int HISTOIRE_T5 { get; set; }
	public int HISTOIRE_T6 { get; set; }
	public int HISTOIRE_T7 { get; set; }
	public int HISTOIRE_T8 { get; set; }
	public int HISTOIRE_T9 { get; set; }
	public int HISTOIRE_2NDE { get; set; }
	public int HISTOIRE_1A { get; set; }
	public int HISTOIRE_1C { get; set; }
	public int HISTOIRE_1D { get; set; }
	public int HISTOIRE_1L { get; set; }
	public int HISTOIRE_1S { get; set; }
	public int HISTOIRE_1OSE { get; set; }
	public int HISTOIRE_TA { get; set; }
	public int HISTOIRE_TC { get; set; }
	public int HISTOIRE_TD { get; set; }
	public int HISTOIRE_TL { get; set; }
	public int HISTOIRE_TS { get; set; }
	public int HISTOIRE_TOSE { get; set; }
	public int GEOGRAPHIE_T1 { get; set; }
	public int GEOGRAPHIE_T2 { get; set; }
	public int GEOGRAPHIE_T3 { get; set; }
	public int GEOGRAPHIE_T4 { get; set; }
	public int GEOGRAPHIE_T5 { get; set; }
	public int GEOGRAPHIE_T6 { get; set; }
	public int GEOGRAPHIE_T7 { get; set; }
	public int GEOGRAPHIE_T8 { get; set; }
	public int GEOGRAPHIE_T9 { get; set; }
	public int GEOGRAPHIE_2NDE { get; set; }
	public int GEOGRAPHIE_1A { get; set; }
	public int GEOGRAPHIE_1C { get; set; }
	public int GEOGRAPHIE_1D { get; set; }
	public int GEOGRAPHIE_1L { get; set; }
	public int GEOGRAPHIE_1S { get; set; }
	public int GEOGRAPHIE_1OSE { get; set; }
	public int GEOGRAPHIE_TA { get; set; }
	public int GEOGRAPHIE_TC { get; set; }
	public int GEOGRAPHIE_TD { get; set; }
	public int GEOGRAPHIE_TL { get; set; }
	public int GEOGRAPHIE_TS { get; set; }
	public int GEOGRAPHIE_TOSE { get; set; }
	public int MATHS_T1 { get; set; }
	public int MATHS_T2 { get; set; }
	public int MATHS_T3 { get; set; }
	public int MATHS_T4 { get; set; }
	public int MATHS_T5 { get; set; }
	public int MATHS_T6 { get; set; }
	public int MATHS_T7 { get; set; }
	public int MATHS_T8 { get; set; }
	public int MATHS_T9 { get; set; }
	public int MATHS_2NDE { get; set; }
	public int MATHS_1A { get; set; }
	public int MATHS_1C { get; set; }
	public int MATHS_1D { get; set; }
	public int MATHS_1L { get; set; }
	public int MATHS_1S { get; set; }
	public int MATHS_1OSE { get; set; }
	public int MATHS_TA { get; set; }
	public int MATHS_TC { get; set; }
	public int MATHS_TD { get; set; }
	public int MATHS_TL { get; set; }
	public int MATHS_TS { get; set; }
	public int MATHS_TOSE { get; set; }
	public int SVT_T1 { get; set; }
	public int SVT_T2 { get; set; }
	public int SVT_T3 { get; set; }
	public int SVT_T4 { get; set; }
	public int SVT_T5 { get; set; }
	public int SVT_T6 { get; set; }
	public int SVT_T7 { get; set; }
	public int SVT_T8 { get; set; }
	public int SVT_T9 { get; set; }
	public int SVT_2NDE { get; set; }
	public int SVT_1A { get; set; }
	public int SVT_1C { get; set; }
	public int SVT_1D { get; set; }
	public int SVT_1L { get; set; }
	public int SVT_1S { get; set; }
	public int SVT_1OSE { get; set; }
	public int SVT_TA { get; set; }
	public int SVT_TC { get; set; }
	public int SVT_TD { get; set; }
	public int SVT_TL { get; set; }
	public int SVT_TS { get; set; }
	public int SVT_TOSE { get; set; }
	public int PHYSIQUE_T6 { get; set; }
	public int PHYSIQUE_T7 { get; set; }
	public int PHYSIQUE_T8 { get; set; }
	public int PHYSIQUE_T9 { get; set; }
	public int PHYSIQUE_2NDE { get; set; }
	public int PHYSIQUE_1A { get; set; }
	public int PHYSIQUE_1C { get; set; }
	public int PHYSIQUE_1D { get; set; }
	public int PHYSIQUE_1L { get; set; }
	public int PHYSIQUE_1S { get; set; }
	public int PHYSIQUE_1OSE { get; set; }
	public int PHYSIQUE_TA { get; set; }
	public int PHYSIQUE_TC { get; set; }
	public int PHYSIQUE_TD { get; set; }
	public int PHYSIQUE_TL { get; set; }
	public int PHYSIQUE_TS { get; set; }
	public int PHYSIQUE_TOSE { get; set; }
	public int CHIMIE_T6 { get; set; }
	public int CHIMIE_T7 { get; set; }
	public int CHIMIE_T8 { get; set; }
	public int CHIMIE_T9 { get; set; }
	public int CHIMIE_2NDE { get; set; }
	public int CHIMIE_1A { get; set; }
	public int CHIMIE_1C { get; set; }
	public int CHIMIE_1D { get; set; }
	public int CHIMIE_1L { get; set; }
	public int CHIMIE_1S { get; set; }
	public int CHIMIE_1OSE { get; set; }
	public int CHIMIE_TA { get; set; }
	public int CHIMIE_TC { get; set; }
	public int CHIMIE_TD { get; set; }
	public int CHIMIE_TL { get; set; }
	public int CHIMIE_TS { get; set; }
	public int CHIMIE_TOSE { get; set; }
	public int ANGLAIS_T6 { get; set; }
	public int ANGLAIS_T7 { get; set; }
	public int ANGLAIS_T8 { get; set; }
	public int ANGLAIS_T9 { get; set; }
	public int ANGLAIS_2NDE { get; set; }
	public int ANGLAIS_1A { get; set; }
	public int ANGLAIS_1C { get; set; }
	public int ANGLAIS_1D { get; set; }
	public int ANGLAIS_1L { get; set; }
	public int ANGLAIS_1S { get; set; }
	public int ANGLAIS_1OSE { get; set; }
	public int ANGLAIS_TA { get; set; }
	public int ANGLAIS_TC { get; set; }
	public int ANGLAIS_TD { get; set; }
	public int ANGLAIS_TL { get; set; }
	public int ANGLAIS_TS { get; set; }
	public int ANGLAIS_TOSE { get; set; }
	public int ALLEMAND_2NDE { get; set; }
	public int ALLEMAND_1A { get; set; }
	public int ALLEMAND_1C { get; set; }
	public int ALLEMAND_1D { get; set; }
	public int ALLEMAND_1L { get; set; }
	public int ALLEMAND_1S { get; set; }
	public int ALLEMAND_1OSE { get; set; }
	public int ALLEMAND_TA { get; set; }
	public int ALLEMAND_TC { get; set; }
	public int ALLEMAND_TD { get; set; }
	public int ALLEMAND_TL { get; set; }
	public int ALLEMAND_TS { get; set; }
	public int ALLEMAND_TOSE { get; set; }
	public int ESPAGNOL_2NDE { get; set; }
	public int ESPAGNOL_1A { get; set; }
	public int ESPAGNOL_1C { get; set; }
	public int ESPAGNOL_1D { get; set; }
	public int ESPAGNOL_1L { get; set; }
	public int ESPAGNOL_1S { get; set; }
	public int ESPAGNOL_1OSE { get; set; }
	public int ESPAGNOL_TA { get; set; }
	public int ESPAGNOL_TC { get; set; }
	public int ESPAGNOL_TD { get; set; }
	public int ESPAGNOL_TL { get; set; }
	public int ESPAGNOL_TS { get; set; }
	public int ESPAGNOL_TOSE { get; set; }
	public int RUSSE_2NDE { get; set; }
	public int RUSSE_1A { get; set; }
	public int RUSSE_1C { get; set; }
	public int RUSSE_1D { get; set; }
	public int RUSSE_1L { get; set; }
	public int RUSSE_1S { get; set; }
	public int RUSSE_1OSE { get; set; }
	public int RUSSE_TA { get; set; }
	public int RUSSE_TC { get; set; }
	public int RUSSE_TD { get; set; }
	public int RUSSE_TL { get; set; }
	public int RUSSE_TS { get; set; }
	public int RUSSE_TOSE { get; set; }
	public int PHILO_2NDE { get; set; }
	public int PHILO_1A { get; set; }
	public int PHILO_1C { get; set; }
	public int PHILO_1D { get; set; }
	public int PHILO_1L { get; set; }
	public int PHILO_1S { get; set; }
	public int PHILO_1OSE { get; set; }
	public int PHILO_TA { get; set; }
	public int PHILO_TC { get; set; }
	public int PHILO_TD { get; set; }
	public int PHILO_TL { get; set; }
	public int PHILO_TS { get; set; }
	public int PHILO_TOSE { get; set; }
	public int SES_2NDE { get; set; }
	public int SES_1A { get; set; }
	public int SES_1C { get; set; }
	public int SES_1D { get; set; }
	public int SES_1L { get; set; }
	public int SES_1S { get; set; }
	public int SES_1OSE { get; set; }
	public int SES_TA { get; set; }
	public int SES_TC { get; set; }
	public int SES_TD { get; set; }
	public int SES_TL { get; set; }
	public int SES_TS { get; set; }
	public int SES_TOSE { get; set; }
	public int ARTS_2NDE { get; set; }
	public int ARTS_1A { get; set; }
	public int ARTS_1C { get; set; }
	public int ARTS_1D { get; set; }
	public int ARTS_1L { get; set; }
	public int ARTS_1S { get; set; }
	public int ARTS_1OSE { get; set; }
	public int ARTS_TA { get; set; }
	public int ARTS_TC { get; set; }
	public int ARTS_TD { get; set; }
	public int ARTS_TL { get; set; }
	public int ARTS_TS { get; set; }
	public int ARTS_TOSE { get; set; }
	public int EAC_T6 { get; set; }
	public int EAC_T7 { get; set; }
	public int EAC_T8 { get; set; }
	public int EAC_T9 { get; set; }
	public int EAC_2NDE { get; set; }
	public int EAC_1A { get; set; }
	public int EAC_1C { get; set; }
	public int EAC_1D { get; set; }
	public int EAC_1L { get; set; }
	public int EAC_1S { get; set; }
	public int EAC_1OSE { get; set; }
	public int EAC_TA { get; set; }
	public int EAC_TC { get; set; }
	public int EAC_TD { get; set; }
	public int EAC_TL { get; set; }
	public int EAC_TS { get; set; }
	public int EAC_TOSE { get; set; }
	public int EPS_T6 { get; set; }
	public int EPS_T7 { get; set; }
	public int EPS_T8 { get; set; }
	public int EPS_T9 { get; set; }
	public int EPS_2NDE { get; set; }
	public int EPS_1A { get; set; }
	public int EPS_1C { get; set; }
	public int EPS_1D { get; set; }
	public int EPS_1L { get; set; }
	public int EPS_1S { get; set; }
	public int EPS_1OSE { get; set; }
	public int EPS_TA { get; set; }
	public int EPS_TC { get; set; }
	public int EPS_TD { get; set; }
	public int EPS_TL { get; set; }
	public int EPS_TS { get; set; }
	public int EPS_TOSE { get; set; }
	public int INFO_TICE_T6 { get; set; }
	public int INFO_TICE_T7 { get; set; }
	public int INFO_TICE_T8 { get; set; }
	public int INFO_TICE_T9 { get; set; }
	public int INFO_TICE_2NDE { get; set; }
	public int INFO_TICE_1A { get; set; }
	public int INFO_TICE_1C { get; set; }
	public int INFO_TICE_1D { get; set; }
	public int INFO_TICE_1L { get; set; }
	public int INFO_TICE_1S { get; set; }
	public int INFO_TICE_1OSE { get; set; }
	public int INFO_TICE_TA { get; set; }
	public int INFO_TICE_TC { get; set; }
	public int INFO_TICE_TD { get; set; }
	public int INFO_TICE_TL { get; set; }
	public int INFO_TICE_TS { get; set; }
	public int INFO_TICE_TOSE { get; set; }
	public int IC_FFMOM_T1 { get; set; }
	public int IC_FFMOM_T2 { get; set; }
	public int IC_FFMOM_T3 { get; set; }
	public int IC_FFMOM_T4 { get; set; }
	public int IC_FFMOM_T5 { get; set; }
	public int IC_FFMOM_T6 { get; set; }
	public int IC_FFMOM_T7 { get; set; }
	public int IC_FFMOM_T8 { get; set; }
	public int IC_FFMOM_T9 { get; set; }
	public int IC_FFMOM_2NDE { get; set; }
	public int IC_FFMOM_1A { get; set; }
	public int IC_FFMOM_1C { get; set; }
	public int IC_FFMOM_1D { get; set; }
	public int IC_FFMOM_1L { get; set; }
	public int IC_FFMOM_1S { get; set; }
	public int IC_FFMOM_1OSE { get; set; }
	public int IC_FFMOM_TA { get; set; }
	public int IC_FFMOM_TC { get; set; }
	public int IC_FFMOM_TD { get; set; }
	public int IC_FFMOM_TL { get; set; }
	public int IC_FFMOM_TS { get; set; }
	public int IC_FFMOM_TOSE { get; set; }
	public int PPO_T1 { get; set; }
	public int PPO_T2 { get; set; }
	public int PPO_T3 { get; set; }
	public int PPO_T4 { get; set; }
	public int PPO_T5 { get; set; }
	public int PPO_T6 { get; set; }
	public int PPO_T7 { get; set; }
	public int PPO_T8 { get; set; }
	public int PPO_T9 { get; set; }
	public int PPO_2NDE { get; set; }
	public int PPO_1A { get; set; }
	public int PPO_1C { get; set; }
	public int PPO_1D { get; set; }
	public int PPO_1L { get; set; }
	public int PPO_1S { get; set; }
	public int PPO_1OSE { get; set; }
	public int PPO_TA { get; set; }
	public int PPO_TC { get; set; }
	public int PPO_TD { get; set; }
	public int PPO_TL { get; set; }
	public int PPO_TS { get; set; }
	public int PPO_TOSE { get; set; }
	public int GUIDE_ENS_T1 { get; set; }
	public int GUIDE_ENS_T2 { get; set; }
	public int GUIDE_ENS_T3 { get; set; }
	public int GUIDE_ENS_T4 { get; set; }
	public int GUIDE_ENS_T5 { get; set; }
	public int GUIDE_ENS_T6 { get; set; }
	public int GUIDE_ENS_T7 { get; set; }
	public int GUIDE_ENS_T8 { get; set; }
	public int GUIDE_ENS_T9 { get; set; }
	public int GUIDE_ENS_2NDE { get; set; }
	public int GUIDE_ENS_1A { get; set; }
	public int GUIDE_ENS_1C { get; set; }
	public int GUIDE_ENS_1D { get; set; }
	public int GUIDE_ENS_1L { get; set; }
	public int GUIDE_ENS_1S { get; set; }
	public int GUIDE_ENS_1OSE { get; set; }
	public int GUIDE_ENS_TA { get; set; }
	public int GUIDE_ENS_TC { get; set; }
	public int GUIDE_ENS_TD { get; set; }
	public int GUIDE_ENS_TL { get; set; }
	public int GUIDE_ENS_TS { get; set; }
	public int GUIDE_ENS_TOSE { get; set; }
	public int GUIDE_CRAN_T1 { get; set; }
	public int GUIDE_CRAN_T2 { get; set; }
	public int GUIDE_CRAN_T3 { get; set; }
	public int GUIDE_CRAN_T4 { get; set; }
	public int GUIDE_CRAN_T5 { get; set; }
	public int GUIDE_CRAN_T6 { get; set; }
	public int GUIDE_CRAN_T7 { get; set; }
	public int GUIDE_CRAN_T8 { get; set; }
	public int GUIDE_CRAN_T9 { get; set; }
	public int GUIDE_CRAN_2NDE { get; set; }
	public int GUIDE_CRAN_1A { get; set; }
	public int GUIDE_CRAN_1C { get; set; }
	public int GUIDE_CRAN_1D { get; set; }
	public int GUIDE_CRAN_1L { get; set; }
	public int GUIDE_CRAN_1S { get; set; }
	public int GUIDE_CRAN_1OSE { get; set; }
	public int GUIDE_CRAN_TA { get; set; }
	public int GUIDE_CRAN_TC { get; set; }
	public int GUIDE_CRAN_TD { get; set; }
	public int GUIDE_CRAN_TL { get; set; }
	public int GUIDE_CRAN_TS { get; set; }
	public int GUIDE_CRAN_TOSE { get; set; }
	public int AUTRES_MANUELS_T1 { get; set; }
	public int AUTRES_MANUELS_T2 { get; set; }
	public int AUTRES_MANUELS_T3 { get; set; }
	public int AUTRES_MANUELS_T4 { get; set; }
	public int AUTRES_MANUELS_T5 { get; set; }
	public int AUTRES_MANUELS_T6 { get; set; }
	public int AUTRES_MANUELS_T7 { get; set; }
	public int AUTRES_MANUELS_T8 { get; set; }
	public int AUTRES_MANUELS_T9 { get; set; }
	public int AUTRES_MANUELS_2NDE { get; set; }
	public int AUTRES_MANUELS_1A { get; set; }
	public int AUTRES_MANUELS_1C { get; set; }
	public int AUTRES_MANUELS_1D { get; set; }
	public int AUTRES_MANUELS_1L { get; set; }
	public int AUTRES_MANUELS_1S { get; set; }
	public int AUTRES_MANUELS_1OSE { get; set; }
	public int AUTRES_MANUELS_TA { get; set; }
	public int AUTRES_MANUELS_TC { get; set; }
	public int AUTRES_MANUELS_TD { get; set; }
	public int AUTRES_MANUELS_TL { get; set; }
	public int AUTRES_MANUELS_TS { get; set; }
	public int AUTRES_MANUELS_TOSE { get; set; }
};